pub mod dashboard;
pub mod scan;
pub mod scans;
pub mod results;
pub mod tools;
pub mod settings;
pub mod reports;
pub mod schedules;
pub mod welcome;

pub use dashboard::DashboardPage;
pub use scan::ScanPage;
pub use scans::ScansPage;
pub use results::ResultsPage;
pub use tools::ToolsPage;
pub use settings::SettingsPage;
pub use reports::ReportsPage;
pub use schedules::SchedulesPage;
pub use welcome::WelcomePage;
